# Generated by Django 4.2.4 on 2023-09-13 17:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('license_plate', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='License plate can only contain alphanumeric characters.', regex='^[a-zA-Z0-9]*$')])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='accounts.carowner')),
            ],
        ),
    ]
